### ISSUE TITLE
Is it possible to specify to run Applescript on modifier key press?

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-repos#15] opened 2017-07-29 20:55 UTC
I would like to run this Applescript when fn modifier key is held down and result is picked.

```Applescript
tell application "iTerm"
	if exists window 1 then
		tell current window
			tell current session to write text "cd {query}"
		end tell
	else
		create window with default profile
		tell current window
			tell current session to write text "cd {query}"
		end tell
	end if
end tell
tell application "System Events"
	if frontmost of process "iTerm2" is false then key code 13 using {option down, control down, shift down, command down}
end tell
```

This will cd to the path of the git project from my current iTerm tab. 

It would be amazing if it would be possible to add this as it will save me so much time. Thank you.

**Comment by deanishe** [comment] 2017-07-30 05:05
Save your script as an application and point the workflow at that.

**Comment by nikitavoloboev** [comment] 2017-07-30 08:50
How do I get the path that your script filter gets to pass into the Automator workflow?

I have this automator applescript : 

![2017-07-30 at 10 49](https://user-images.githubusercontent.com/6391776/28751982-dba98b72-7514-11e7-8d07-c93f517453f8.png)

Since {query} is Alfred's way of passing input, I can't find a way to do the same in Automator.

**Comment by nikitavoloboev** [comment] 2017-07-30 09:07
Found [this](https://www.questarter.com/q/in-automator-pass-path-variable-into-applescript-13_189107.html). But then it seems that I can't pass anything to it if I save it to .app 

![2017-07-30 at 11 07](https://user-images.githubusercontent.com/6391776/28752067-3da8abee-7517-11e7-8fe4-e52b1b2af0fb.png)

**Comment by deanishe** [comment] 2017-07-30 10:56
Niki, please read errors before posting them.

That dialog says your script won't get any input when run *inside Automator*.

**Comment by nikitavoloboev** [comment] 2017-07-30 11:05
Yeah but I tried it outside too and it didn't work. :(

**Comment by nikitavoloboev** [comment] 2017-07-30 11:32
Running it outside just says this : 

![2017-07-30 at 13 32](https://user-images.githubusercontent.com/6391776/28752968-91265a28-752b-11e7-8375-b49f078f4c0a.png)

Which is not very helpful. :(

**Comment by deanishe** [comment] 2017-07-31 06:14
> Which is not very helpful

Why don't you try reading the first screenshot you posted? It tells you exactly how to run the script in Automator. And when you've done that, pay attention to the data types. You can't just add a list of HFS paths to a shell command and expect it to work.

Closing as unrelated to the workflow.

**Closed by deanishe** 2017-07-31 06:14 UTC

**Comment by nikitavoloboev** [comment] 2017-08-01 11:42
This script worked for me 

```Applescript
 on run {input, parameters}

  set cmdStr to "cd " & (POSIX path of input)
  
  tell application "iTerm"
    if exists window 1 then
      tell current window
        tell current session to write text cmdStr
              end tell
    else
      create window with default profile
      tell current window
        tell current session to write text cmdStr
      end tell
    end if
  end tell
```

But you probably already knew that. Thanks for the pointers, this is really cool to see it work.

**Comment by nikitavoloboev** [comment] 2018-02-04 15:19
I have one issue with the above solution and that is that there is a certain (~ 2) seconds delay when activating this applescript. I am not sure if it's because it is calling the Automator application which contains this Applescript or the Applescript itself.

I have saved the Applescript as an app as you proposed and then call it on a modifier keypress:

```Bash
{
  "__workflow_last_version": "2.1.2",
  "app_alt": "cdToiTerm",
  "app_cmd": "Finder",
  "app_shift": "Tower",
  "app_fn": "Safari",
  "app_default": "Sublime Text",
  "app_ctrl": "Visual Studio Code",
```

Would it perhaps be possible to call Applescript code directly so that Alfred Repos can support it? Or that is not the reason that causes this delay?

Ideally I wish it would activate as fast as [this workflow](https://github.com/nikitavoloboev/small-workflows/blob/master/folder-search/Folder%20search.alfredworkflow?raw=true). So it writes the path to the iTerm window immediately upon activating.

Thank you a lot for any help on this.

**Comment by deanishe** [comment] 2018-02-04 16:38
> I am not sure if it's because it is calling the Automator application which contains this Applescript or the Applescript itself.

Well why don't you try and figure that out for yourself before asking me to spend my evening adding features to my workflow?

> Ideally I wish it would activate as fast as this workflow.

It can't. I'll leave it up to you to figure out why.

**Comment by nikitavoloboev** [comment] 2018-02-04 17:16
Will try to add Applescript support to the workflow if only for myself. I looked at the code and I think I can do it.

One advice I can give that I think would be really useful to people who want to contribute to your workflows is letting users know what the best approach is for modifying the workflow is. I try to do it [like this](https://github.com/nikitavoloboev/alfred-learn-anything#developing).

For this workflow, what I do now is modify on the code internally to the workflow but I am not sure if that is the best approach. Another approach would probably me cloning this repo, then changing info.plist `key` to something like `net.deanishe.alfred-git-repos.dev`, then symlinking the workflow with your script and working on that. Again I am not sure what the 'best' way is but I guess that would be the right way to do it.

**Comment by deanishe** [comment] 2018-02-04 17:42
> And there it is instant. So the 'issue' is with the workflow.

No, the issue is with you. Compare:

```
Keyboard Maestro Script
-----------------------
Running application (Keyboard Maestro) -> script in memory -> run it.

Alfred-Repos
------------
Running application (Alfred) -> launch workflow -> load settings and look up app -> Call `open` to run app -> find application on disk -> launch Automator wrapper app -> load script from disk -> run it.
```
This is *exactly* the same as the "Searchio! is slower than Hammerspoon" issue you posted.

**Comment by deanishe** [comment] 2018-02-04 17:53
> Wouldn't this work?

I don't know. I've no idea what happens when a Script Filter defines modifiers in its feedback but there's also an action assigned to that modifier in Alfred's UI.

**Comment by nikitavoloboev** [comment] 2018-02-04 17:58
Oh wow. This actually solves it. This is the [changed workflow](https://transfer.sh/13O1ne/Git-Repos.alfredworkflow).

It still has the same delay as it does the lookup though so yeah my plan doesn't work. Oh well.

Thanks for the help.

**Comment by nikitavoloboev** [comment] 2018-02-04 18:10
Oh nvm. I am just stupid.

[This works](https://transfer.sh/Zbaty/Git-Repos.alfredworkflow) in case you want the same functionality.

Thank you very much @deanishe

**Comment by deanishe** [comment] 2018-02-04 18:51
> in case you want the same functionality

No. I don't store the applications in the settings file and run them via Python for no reason.
